#
# RISC-V system tests
#

TEST_SRC = $(SRC_PATH)/tests/tcg/riscv64
VPATH += $(TEST_SRC)

LINK_SCRIPT = $(TEST_SRC)/semihost.ld
LDFLAGS = -T $(LINK_SCRIPT)
CFLAGS += -g -Og

%.o: %.S
	$(CC) $(CFLAGS) $< -Wa,--noexecstack -c -o $@
%: %.o $(LINK_SCRIPT)
	$(LD) $(LDFLAGS) $< -o $@

QEMU_OPTS += -M virt -display none -semihosting -device loader,file=

EXTRA_RUNS += run-issue1060
run-issue1060: issue1060
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-mepc-masking
run-test-mepc-masking: test-mepc-masking
	$(call run-test, $<, $(QEMU) $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-minstret-ecall
run-test-minstret-ecall: test-minstret-ecall
	$(call run-test, $<, $(QEMU) -icount shift=1 $(QEMU_OPTS)$<)

EXTRA_RUNS += run-plugin-doubletrap
run-plugin-doubletrap: doubletrap
	$(call run-test, $<, \
	  $(QEMU) -plugin ../plugins/libdiscons.so -d plugin -D $<.pout \
	  $(QEMU_OPTS)$<)

EXTRA_RUNS += run-plugin-interruptedmemory
run-plugin-interruptedmemory: interruptedmemory
	$(call run-test, $<, \
	  $(QEMU) -plugin ../plugins/libdiscons.so -d plugin -D $<.pout \
	  $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-crc32
comma:= ,
run-test-crc32: test-crc32
	$(call run-test, $<, $(QEMU) -cpu rv64$(comma)xlrbr=true $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-xtheadvector
test-xtheadvector: test-xtheadvector.o
run-test-xtheadvector: test-xtheadvector
	$(call run-test, $<, $(QEMU) -cpu thead-c910 $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-thead-c910-pmu
test-thead-c910-pmu: test-thead-c910-pmu.o
run-test-thead-c910-pmu: test-thead-c910-pmu
	$(call run-test, $<, $(QEMU) -icount shift=0 \
	  -cpu thead-c910 $(QEMU_OPTS)$<)

THEAD_C910_MM_MARCH = \
	-march=rv64imafdc_zfh_xtheadfmemidx_xtheadmemidx_xtheadmempair
CLEANFILES += test-thead-c910-mxstatus-mm test-thead-c910-mm-priority \
	test-thead-c910-maee

test-thead-c910-mxstatus-mm: test-thead-c910-mxstatus-mm.S $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(THEAD_C910_MM_MARCH) $< -Wa,--noexecstack -c -o $@.o
	$(LD) $(LDFLAGS) $@.o -o $@

EXTRA_RUNS += run-test-thead-c910-mxstatus-mm
run-test-thead-c910-mxstatus-mm: test-thead-c910-mxstatus-mm
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

test-thead-c910-mm-priority: test-thead-c910-mm-priority.S $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(THEAD_C910_MM_MARCH) $< -Wa,--noexecstack -c -o $@.o
	$(LD) $(LDFLAGS) $@.o -o $@

EXTRA_RUNS += run-test-thead-c910-mm-priority
run-test-thead-c910-mm-priority: test-thead-c910-mm-priority
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

test-thead-c910-maee: test-thead-c910-maee.S $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(THEAD_C910_MM_MARCH) $< -Wa,--noexecstack -c -o $@.o
	$(LD) $(LDFLAGS) $@.o -o $@

EXTRA_RUNS += run-test-thead-c910-maee
run-test-thead-c910-maee: test-thead-c910-maee
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

EXTRA_RUNS += run-test-thead-c900-clint
test-thead-c900-clint: test-thead-c900-clint.o
run-test-thead-c900-clint: test-thead-c900-clint
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

EXTRA_RUNS += run-test-thead-c900-plic
test-thead-c900-plic: test-thead-c900-plic.o
run-test-thead-c900-plic: test-thead-c900-plic
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

EXTRA_RUNS += run-test-dw-apb-uart
test-dw-apb-uart: test-dw-apb-uart.o
run-test-dw-apb-uart: test-dw-apb-uart
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

EXTRA_RUNS += run-test-dw-apb-timer
test-dw-apb-timer: test-dw-apb-timer.o
run-test-dw-apb-timer: test-dw-apb-timer
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -semihosting -bios $<)

EXTRA_RUNS += run-test-beaglev-ahead-smp
test-beaglev-ahead-smp: test-beaglev-ahead-smp.o
run-test-beaglev-ahead-smp: test-beaglev-ahead-smp
	$(call run-test, $<, $(QEMU) -M beaglev-ahead -display none \
	  -monitor none -serial file:$<.out -semihosting -bios $<)
	$(call quiet-command, printf '0123\n' | diff - $<.out, \
	  DIFF,$<.out with expected four-hart transcript)

# Zicclsm: misaligned load/store support. Assemble one source twice: the
# default build expects every misaligned access to succeed (zicclsm=true),
# the -DZICCLSM_DISABLED build expects every one to trap (zicclsm=false).
ZICCLSM_MARCH = -march=rv64gcv_zfh
CLEANFILES += test-zicclsm test-zicclsm-off

test-zicclsm: test-zicclsm.S $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(ZICCLSM_MARCH) $< -Wa,--noexecstack -c -o test-zicclsm.o
	$(LD) $(LDFLAGS) test-zicclsm.o -o $@

test-zicclsm-off: test-zicclsm.S $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(ZICCLSM_MARCH) -DZICCLSM_DISABLED $< -Wa,--noexecstack -c -o test-zicclsm-off.o
	$(LD) $(LDFLAGS) test-zicclsm-off.o -o $@

EXTRA_RUNS += run-test-zicclsm
run-test-zicclsm: test-zicclsm
	$(call run-test, $<, $(QEMU) -cpu rv64$(comma)v=true$(comma)zfh=true$(comma)zicclsm=true $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-zicclsm-off
run-test-zicclsm-off: test-zicclsm-off
	$(call run-test, $<, $(QEMU) -cpu rv64$(comma)v=true$(comma)zfh=true$(comma)zicclsm=false $(QEMU_OPTS)$<)

EXTRA_RUNS += run-test-misa-w
run-test-misa-w: test-misa-w
	$(call run-test, $<, $(QEMU) -cpu rv64$(comma)x-misa-w=true$(comma)c=true$(comma)v=true $(QEMU_OPTS)$<)

# We don't currently support the multiarch system tests
undefine MULTIARCH_TESTS
